
package cn.edu.nju.soap.biz;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StudentPortType", targetNamespace = "http://jw.nju.edu.cn/wsdl")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StudentPortType {


    /**
     * 
     * @param parameters
     * @return
     *     returns cn.edu.nju.soap.biz.GetStudentResponse
     * @throws ServiceError
     */
    @WebMethod
    @WebResult(name = "getStudentResponse", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "parameters")
    public GetStudentResponse getStudentInfo(
        @WebParam(name = "getStudentRequest", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "parameters")
        GetStudentRequest parameters)
        throws ServiceError
    ;

    /**
     * 
     * @param parameters
     * @return
     *     returns cn.edu.nju.soap.biz.CheckInResponse
     * @throws ServiceError
     */
    @WebMethod
    @WebResult(name = "checkInResponse", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "parameters")
    public CheckInResponse checkIn(
        @WebParam(name = "checkInRequest", targetNamespace = "http://jw.nju.edu.cn/wsdl", partName = "parameters")
        CheckInRequest parameters)
        throws ServiceError
    ;

}
